use_frameworks!

platform :ios, '10.0'

target 'PKHMultiPeer_Example' do
  pod 'PKHMultiPeer', :path => '../'
  pod 'SnapKit'

  target 'PKHMultiPeer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
